# Copyright (C) 2014 Dell, Inc.
# 
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

########## General Notes
# 
# This config file is used by the Doradus server at startup. Most of these configuration parameters
# can be overridden via command-line options by placing a dash before the parameter name (e.g.,
# "-dbport 9876"). The following rules apply to this yaml file:
#
#   1) Comments begin with a # just like this line.
#   2) Outer-most parameters should start in column 1 with no dash.
#   3) Most parameters use the format <name>: <value>. But some parameters have subparameters.
#   4) An empty value consists of a pair of quotes. (e.g., sstable_compression: "").
#   5) Child parameters, when used, must begin on a new line with one or more leading spaces, then
#      a dash, then a space, then the parameter name and value.
#

########## Doradus Service Parameters
# 
# storage_services: This parameter defines which storage service modules are started and therefore
# available to applications. Most Doradus instances will use a single storage service, although
# multiple services can be used. If multiple storage services are listed, the first one becomes the
# default for new applications that don't explicitly set a StorageService option. Two storage
# services are currently available:
#
#   com.dell.doradus.service.olap.OLAPService
#   com.dell.doradus.service.spider.SpiderService
#
# See the Doradus documentation for the features provided by each storage service.
#
storage_services:
    - com.dell.doradus.service.spider.SpiderService
    - com.dell.doradus.service.olap.OLAPService

########## Cassandra Keyspace Parameters
#
# These parameters are used to create the initial Cassandra Keyspace used by Doradus. When Doradus
# starts, if the given Keyspace name doesn't exist, Doradus creates it with the configured options.
# However, once the Keyspace exists, these parameters are not used. Keyspace must be modified via
# Cassandra-level tools. 
#

# keyspace: Name of the Keyspace that contains Doradus-managed data. Default: 'Doradus'.
keyspace: 'Doradus'

# ks_defaults: See Cassandra documentation for details on default keyspace parameters.
ks_defaults:
    - strategy_class: SimpleStrategy
    - strategy_options:
        - replication_factor: "1"   # enclose this value in quotes
    - durable_writes: true
    
########## Cassandra ColumnFamily Parameters
#
# These options are used when new Cassandra ColumnFamilies are created. They are only used when a
# a new CF is created: existing CFs are not modified if these options are changed after they are
# created.

# cf_defaults: See Cassandra and Doradus Administration documentation for recommendations on these
# options.
cf_defaults:
    - compression_options:
        - sstable_compression: ""   # use empty string for "none"
    - gc_grace_seconds: 3600

########## Cassandra Connection Parameters
#
# These parameters affect the Cassandra database node(s) to which Doradus connects.
#

# dbhost: The host name(s) or address(es) of the Cassandra node(s) to connect to. Static IP
# addresses are preferred over host names. If a comma-separated list of hosts is provided, Doradus
# will connect to each one in round-robin fashion, allowing load balancing and failover. Default:
# 'localhost'.
dbhost: 'localhost'

# dbport: The RPC (Thrift) port of the Cassandra database. It must be the same on all nodes.
# Default: 9160.
dbport: 9160

# jmxport: The JMX port of the Cassandra database. It must be the same on all nodes. Note that JMX
# can be configured via runtime options to require authentication and/or TLS/SSL. Default: 7199.
jmxport: 7199

# dbauthenticator: The fully qualified class name of the authenticator class to use when the
# Cassandra Thrift API is configured to require authentication. Default: null (no authentication).
# dbauthenticator: com.dell.doradus.service.db.SimpleAuthenticator

# db_timeout_millis: Database timeout in milliseconds. This time is used both when connecting to
# Cassandra and when performing read/write operations. Default: 60 seconds.
# db_timeout_millis: 60000

# db_connect_retry_wait_millis: Database initial connection retry wait in milliseconds. If the
# initial connection to Cassandra times-out (see db_timeout_millis), Doradus waits this amount of
# time before trying again. Doradus keeps retrying indefinitely under the assumption that Cassandra
# may take a while to start. Default: 5 seconds.
# db_connect_retry_wait_millis: 5000

# max_commit_attempts: Maximum number of times Doradus attempts an update (batch_mutate or row
# remove) call to Cassandra. If an update fails, Doradus waits a while (see retry_wait_millis) and
# tries again, up to this limit. Default: 10.
# max_commit_attempts: 10

# max_read_attempts: Maximum number of times Doradus attempts a read (e.g., get_range_slices) call
# to Cassandra. If a read request fails, Doradus waits a bit (see retry_wait_millis) and tries the
# read again, up to this limit. Default: 3.
max_read_attempts: 7

# max_reconnect_attempts: Maximum number of times Doradus attempts to reconnect to Cassandra after
# a failure. A reconnect is performed if a read or update call fails with an exception that suggests
# that the Cassandra node may be down, not just busy. With each failed reconnect attempt, Doradus
# waits a bit (see retry_wait_millis) and retries, up to this limit. Default: 3.
# max_reconnect_attempts: 3

# retry_wait_millis: The time in milliseconds that Doradus waits after a failed update, read, or
# reconnect request call to Cassandra. This time is multiplied by the attempt #, so Doradus waits a
# little longer with each successive failed call. Default: 5 seconds. See also max_commit_attempts,
# max_read_attempts, and max_reconnect_attempts.
# retry_wait_millis: 5000

# use_cql: Experimental: Set to true to use Cassandra's CQL API insead of Thrift. CQL is only
# available if "start_native_transport: true" is set in cassandra.yaml.  Also, set "dbport" in this
# file to the value of "native_transport_port" in cassandra.yaml, which is normally 9042.
use_cql: false
#dbport: 9042

########## Doradus REST API Parameters
#
# These parameters affect the Doradus REST API.
#

# restaddr: The IP address to which Doradus binds and listens for REST connections. Default is
# '0.0.0.0' which means "any address".
# restaddr: 0.0.0.0

# restport: The port number to which Doradus binds and listens for REST connections. Default is
# 1123.
restport: 1123

# maxconns: The maximum number of simultaneous REST connections allowed. If additional connections
# above this limit is received, they are accepted but queued and don't receive service until another
# connection is closed. Default is 200.
maxconns: 200

# tls: If true it will create the REST connection as a TLS/SSL server. Default is false.
# tls: true

# tls_cipher_suites: If TLS/SSL is enabled, this parameter defines which cipher suites the server
# offers to clients. This is an "include" (or "white") list, which means only these algorithms are
# offered. Only cipher suites available to the JVM are actually offered to clients. The list below
# is the recommended cipher suite for FIPS compliance. See:
#    http://www-archive.mozilla.org/projects/security/pki/nss/ssl/fips-ssl-ciphersuites.html
tls_cipher_suites:
   - TLS_DHE_DSS_WITH_3DES_EDE_CBC_SHA
   - TLS_DHE_DSS_WITH_AES_128_CBC_SHA
   - TLS_DHE_DSS_WITH_AES_256_CBC_SHA
   - TLS_DHE_RSA_WITH_3DES_EDE_CBC_SHA
   - TLS_DHE_RSA_WITH_AES_128_CBC_SHA
   - TLS_DHE_RSA_WITH_AES_256_CBC_SHA
   - TLS_RSA_WITH_3DES_EDE_CBC_SHA
   - TLS_RSA_WITH_AES_128_CBC_SHA
   - TLS_RSA_WITH_AES_256_CBC_SHA
   - TLS_ECDHE_ECDSA_WITH_3DES_EDE_CBC_SHA
   - TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA
   - TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA
   - TLS_ECDHE_RSA_WITH_3DES_EDE_CBC_SHA
   - TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA
   - TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA
   - TLS_ECDH_ECDSA_WITH_3DES_EDE_CBC_SHA
   - TLS_ECDH_ECDSA_WITH_AES_128_CBC_SHA
   - TLS_ECDH_ECDSA_WITH_AES_256_CBC_SHA
   - TLS_ECDH_RSA_WITH_3DES_EDE_CBC_SHA
   - TLS_ECDH_RSA_WITH_AES_128_CBC_SHA
   - TLS_ECDH_RSA_WITH_AES_256_CBC_SHA
   
# clientauthentication: If true mutual client/server authentication is required. Default is false.
# clientauthentication: false

# keystore: Defines the path of the keystore file that contains the private SSL certificate used
# when 'tls' is true. Default is system setting.
# keystore: config/keystore

# keystorepassword: Defines the password used to protect the keystore file. Default is system
# setting.
# keystorepassword: changeit

# truststore: Defines the path name of the truststore file the trusted client certificates when
# 'tls' and 'clientauthentication' are both true. Default is system setting.
# truststore: config/truststore

# truststorepassword: Defines the password that protects the truststore file. Default is system
# setting.
# truststorepassword: password

# max_request_size: Defines the maximum size of an input entity (message) that will be accepted in
# requests. If a request has a content-length larger than this, the request is rejected and the
# socket is closed. Default is 50MB.
# max_request_size: 52428800

########## Doradus Query Parameters
#
# These parameters affect the operation of Doradus query execution.
#

# aggr_separate_search: <flag>
# Define separate search flag for aggregates
# Default flag is false
aggr_separate_search: false

# aggr_concurrent_threads: <#>
# Define number of concurrent threads for aggregates
# Default is 8
aggr_concurrent_threads: 0

# dbesoptions_entityBuffer: <#>
# number of entities being pre-fetched with scalar values
# Default is 1000
dbesoptions_entityBuffer: 1000

# dbesoptions_linkBuffer: <#>
# number of pre-fetched references of the same link field for one entity if the current buffer is empty
# Default is 1000
dbesoptions_linkBuffer: 1000

# dbesoptions_initialLinkBuffer: <#>
# number of pre-fetched references of the same link field for every cached entity when the link values asked for one entity
# Default is 10
dbesoptions_initialLinkBuffer: 10

# dbesoptions_initialLinkBufferDimension: <#>
# number of entities the initial links will be pre-fetched for
# Default is 1000
dbesoptions_initialLinkBufferDimension: 1000

# dbesoptions_initialScalarBuffer: <#>
# number of pre-fetched scalar values for every cached entity when all scalar fields are requested
# Default is 30
dbesoptions_initialScalarBuffer: 30

# search_default_page_size: Default query page size (used when s=... parameter is missing
# in _query request). Default: 100
search_default_page_size: 100

# l2r_enable: Enable left-to-right algorithm. If set to false, old algorithm is applied. Default is
# true.
l2r_enable: true


########## OLAP Parameters
#
# These parameters control the operation of the OLAP Service.
#

# olap_cache_size_mb: size, in megabytes, allowed for cache of most-recently-used fields
# simultaneously loaded into RAM. If it is exceeded, older fields will be un-loaded from memory.
# The default is 100
olap_cache_size_mb: 1000

# olap_loaded_segments: number of most-recently-used segment statistics structures cached.
# Statistics structures are needed to load segment fields; they are small and do not occupy much
# memory. If this value is zero, the default value is 1 million, which is sufficient even if your
# application performs many merges.
# Default is 0, which allows up to 1M segment statistics structures to be loaded.
olap_loaded_segments: 0

# olap_store_cache_size_mb: size, in megabytes, of the cached raw OLAP data, such as values of text
# field. It does not affect shards loaded in memory. 0 means they are not cached.
# Default is 100
olap_file_cache_size_mb: 100

# olap_query_cache_size_mb: size, in megabytes, of the cached search results. Each cached result
# takes 1 bit per each document in the table. 0 means no caching.
# Default is 100
olap_query_cache_size_mb: 100

# olap_cf_defaults: Options used to create the OLAP ColumnFamily. This CF is only created when the
# server is first started for a new database. If these options are changed, an existing OLAP CF is
# not modified to match. See Cassandra and Doradus Administration documentation for details about
# these options.
olap_cf_defaults:
    - compression_options:
        - sstable_compression:  "" # use empty string for "none"
    - gc_grace_seconds: 3600


########## Doradus Spider Parameters
#
# These parameters affect the operation of the Spider Service.
#

# batch_mutation_threshold: Defines the maximum number of mutations a batch update will queue
# before flushing to the database. After the mutation are generated for each object in a batch
# update, Spider checks to see if this threshold has been met and flushes the current mutation
# batch if it has. Larger values improve performance by reducing Cassandra round trips, but they
# require larger Thrift API buffer sizes. The default is 10,000.
batch_mutation_threshold: 10000


########## Background tasks parameters
#
# max_node_tasks: Maximal number of tasks that can be launched concurrently on one Doradus node.
# If there is no node that can launch a task since all the nodes are busy with max_node_tasks each,
# then the task is skipped, and may be scheduled next time.
# max_node_tasks: 2

# task_exec_delay: Minimum interval (in seconds) between the scheduled time and actual start of the
# task. This delay is used for Doradus nodes to synchronize and to decide which node would perform
# the task. After this initial delay task may be delayed once more for maximum task_exec_delay
# seconds, so actual time interval between scheduled time and actual task start time may be between
# task_exec_delay and 2 * task_exec_delay seconds. Default value for task_exec_delay is 5.
# task_exec_delay: 5

# task_restarts: Number of attempts to restart a task if it was interrupted due to an internal error.
# The task will not be restarted if an external error (like server node fault) occurs.
# The default value for task_restarts is 2.
# task_restarts: 2

# check_interrupting_interval: An interval (in seconds) between consequent analysis of whether a task
# that is executing by this node was interrupted by user request. The default value for
# check_interrupting_interval is 10.
# check_interrupting_interval: 10

# default_schedule: Global default schedule used for all tasks for all applications and tables.
# The value is a cron expression (example: '0 0 31 10 *'). The default is null, which means no
# tasks are automatically scheduled.
# default_schedule: 
